all: clean compile run

compile: main.c
	@echo "compiling..."
	@gcc main.c -o main.out
run:
	@echo ---------------------------
	@./main.out
clean:
	@echo ---------------------------
	@clear
	@rm -f *.out

